apiVersion: v1
kind: Secret
metadata:
  name: franchise-secrets
  namespace: franchise
type: Opaque
data:
  # echo -n 'your-secret' | base64
  SPRING_DATA_MONGODB_USERNAME: YWRtaW4=  # admin
  SPRING_DATA_MONGODB_PASSWORD: YWRtaW4xMjM=  # admin123
